### ISSUE TITLE
Add a heading "Download the app from Appstore(s)" before the store links on homepage - For OSDW 2017

### ISSUE THREAD

**Issue by kashifzaidi1** [codeforpakistan/Messiah-Web#67]
Add a heading "Download the app from Appstore(s)" before the store links on homepage

**Comment by Atif8181** [comment]
Kindly unsubscribe me
Thanks

Sent from my iPhone

On 28 Jan 2017, at 10:46 am, Kashif Zaidi <notifications@github.com<mailto:notifications@github.com>> wrote:


Add a heading "Download the app from Appstore(s) before the store links on homepage"

-

**Comment by kashifzaidi1** [comment]
This issue was moved to kashifzaidi1/Messiah-Web#22

**Comment by ShaneWilton** [comment]
❤️ 💚 💙 💛 💜
